version: '3'
services:
  app:
    image: "cxmcc/webinspect"
    networks:
      - nw
  nginx:
    build: "nginx"
    networks:
      - nw
    depends_on:
      - app
    ports:
      - 8080:80
networks:
  nw:
    driver: bridge
